namespace SmartScannerPro.TestAssets;

using System.Threading;
using System.Threading.Tasks;
using SmartScannerPro.Scanner.Abstractions.Models.Images;

/// <summary>
/// Generates a reusable synthetic scanner document.
/// </summary>
public interface IDocumentGenerator
{
    /// <summary>
    /// Gets the document kind generated by this instance.
    /// </summary>
    DocumentKind Kind { get; }

    /// <summary>
    /// Generates the document as a scanner-compatible raw image.
    /// </summary>
    /// <param name="request">The rendering request.</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>A raw image containing the generated document.</returns>
    Task<RawImage> GenerateAsync(DocumentRenderRequest request, CancellationToken cancellationToken = default);
}
